dataset_add_encoder_length: true
dataset_add_relative_time_idx: true
dataset_encoder_activation_function: relu
dataset_freqeuncy: hour
dataset_group_key:
- "\uAC74\uBB3C\uBC88\uD638"
dataset_known_categoricals: []
dataset_known_real:
- "\uAE30\uC628(C)"
- "\uAC15\uC218\uB7C9(mm)"
- "\uD48D\uC18D(m/s)"
- "\uC2B5\uB3C4(%)"
- hour
- weekday
- "\uB9C8\uD2B8\uD734\uC77C"
- "\uACF5\uD734\uC77C"
- "\uC804\uB825\uC18C\uBE44_lag24"
dataset_max_encoder_length: 72
dataset_max_prediction_length: 24
dataset_min_encoder_length: 24
dataset_min_prediction_length: 6
dataset_seed_number: 0
dataset_static_categoricals:
- "\uAC74\uBB3C\uBC88\uD638"
- "\uAC74\uBB3C\uC720\uD615"
dataset_static_reals:
- "\uC5F0\uBA74\uC801(m2)"
- "\uB0C9\uBC29\uBA74\uC801(m2)"
- "\uD0DC\uC591\uAD11\uC6A9\uB7C9(kW)"
- "ESS\uC800\uC7A5\uC6A9\uB7C9(kWh)"
- "PCS\uC6A9\uB7C9(kW)"
dataset_target: "\uC804\uB825\uC18C\uBE44\uB7C9(kWh)"
dataset_timestamp: "\uC77C\uC2DC"
dataset_timestamp_min: '2022-06-03'
dataset_training_cutoff: 0
dataset_unknown_categoricals: []
dataset_unknown_real:
- "\uC804\uB825\uC18C\uBE44\uB7C9(kWh)"
model_QuantileLoss_para: 1
model_algorithm: tft
model_attention_head_size: 16
model_dropout: 0.5
model_hidden_continuous_size: 16
model_hidden_layer_size: 32
model_labelencodder_embedding:
  "\uAC74\uBB3C\uBC88\uD638": 7
  "\uAC74\uBB3C\uC720\uD615": 10
model_learning_rate: 0.0005
model_log_interval: 10
model_output_size: 7
model_reduce_on_plateau_patience: 10
model_weight_decay: 0.05
trainer_batch_size: 512
trainer_early_stop_min_delta: 0.0005
trainer_early_stop_mode: min
trainer_early_stop_monitor: val_loss
trainer_early_stop_patience: 10
trainer_early_stop_verbose: false
trainer_epoch_size: 500
trainer_gradient_clip_val: 0.1
